# Generated by Django 5.2 on 2026-07-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collects", "0007_alter_collect_created_by"),
        ("payments", "0004_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="collect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="collects.collect",
                verbose_name="Collect",
            ),
        ),
    ]
