# Generated by Django 5.2 on 2025-04-19 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
            },
        ),
        migrations.AddField(
            model_name="collect",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="collect_covers/",
                verbose_name="Обложка",
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("birthday", "День рождения"),
                    ("wedding", "Свадьба"),
                    ("new_year", "Новый год"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=20,
                verbose_name="Повод",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="collected_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Собрано"
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="goal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оставьте пустым для нескончаемого сбора",
                max_digits=12,
                null=True,
                verbose_name="Цель сбора",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="collect",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
