# Generated by Django 5.2 on 2025-04-20 18:06

import collects.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0004_alter_collect_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='collect_covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), collects.validators.validate_file_size], verbose_name='Обложка'),
        ),
    ]
