# Generated by Django 5.2 on 2026-07-03 05:39

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collects", "0005_alter_collect_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="goal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank for an open-ended fundraise.",
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01"))
                ],
                verbose_name="Goal amount",
            ),
        ),
    ]
