#name: CI
#
#on:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.13.2'
#      - name: Upgrade pip & virtualenv
#        run: pip install --upgrade pip virtualenv==20.26.6
#      - name: Install Poetry
#        run: pip install poetry
#      - name: Install dependencies
#        run: poetry install --no-interaction --no-ansi
#      - name: Run tests
#        run: poetry run pytest --maxfail=1 --disable-warnings -q

#  send_message:
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#      - name: Send message
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            Деплой успешно выполнен!
#            Запушил: ${{ github.actor }}
#            Сообщение коммита: ${{ github.event.commits[0].message }}
#            Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}